spring.application.name=orders-service
server.port=8082
server.servlet.context-path=/orders
spring.datasource.url=jdbc:postgresql://localhost:5432/kitchensink
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
marketplace.base-url=http://localhost:8081/marketplace
users.base-url=http://localhost:8083/users
management.endpoints.web.exposure.include=health
