spring.datasource.url=jdbc:postgresql://localhost:5432/kitchensink
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.servlet.context-path=/kitchensink
