name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Only run the latest job per ref
concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build and Test
        working-directory: kitchensink
        run: mvn -B clean verify
      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            kitchensink/**/target/surefire-reports/**
            kitchensink/**/target/failsafe-reports/**
